# https://docs.docker.com/compose/compose-file/compose-file-v3/
version: '3.8'
services:
  mongodb:
    image: 'mongo'
    volumes:
      - 'cachedb:/data/db'
    env_file:
      - ./env/mongo.env
  backend:
    build: ./backend
    ports:
      - 80:80
    volumes:
      - logs:/app/logs
      - /app/node_modules
      - ./backend:/app
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    build: './frontend'
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
volumes:
  cachedb:
  logs:

